### ISSUE TITLE
Error: Failed to install 'LTRpred' from GitHub:   (converted from warning) package ‘amap’ is not available (for R version 3.5.1)

### ISSUE THREAD

**Issue by CristianRiccio** [HajkD/LTRpred#6]
When I run `biocLite("HajkD/LTRpred")`, I get the following message:

`Failed to install 'LTRpred' from GitHub:   (converted from warning) package ‘amap’ is not available (for R version 3.5.1)`

Does that mean that LTRpred cannot be installed on R version 3.5.1? Do you have a recommended R version?

I work on macOS High Sierra.

**Comment by HajkD** [comment]
Hi @CristianRiccio 

As you can see from the [amap package repo](https://cran.r-project.org/web/packages/amap/index.html), the most recent version of `amap` requires at least R 3.6.0. 

However, I now moved the `amap` package to a suggested package dependency rather than a required package dependency in `LTRpred` which should allow you to install `LTRpred` with R 3.5.1.

I hope this helps?

Cheers,
Hajk

**Comment by CristianRiccio** [comment]
Thanks, I now have another error:

```
** package ‘data.table’ successfully unpacked and MD5 sums checked
** libs
clang -I"/Users/user/anaconda/envs/ltrpred/lib/R/include" -DNDEBUG   -I/Users/user/anaconda/envs/ltrpred/include   -fPIC  -mmacosx-version-min=10.9  -m64 -fPIC  -c assign.c -o assign.o
In file included from assign.c:1:
In file included from ./data.table.h:1:
/Users/user/anaconda/envs/ltrpred/lib/R/include/R.h:55:11: fatal error: 'stdlib.h' file not found
# include <stdlib.h> /* Not used by R itself, but widely assumed in packages */
          ^~~~~~~~~~
1 error generated.
make: *** [/Users/user/anaconda/envs/ltrpred/lib/R/etc/Makeconf:160: assign.o] Error 1
ERROR: compilation failed for package ‘data.table’
```
Is it because my C compiler is clang instead of gcc?

**Comment by HajkD** [comment]
Could be because of the compiler ...

Short googling gave me:

https://github.com/Rdatatable/data.table/issues/3072

https://stackoverflow.com/questions/52469529/clang-error-in-installing-data-table-in-mac-os-high-sierra

https://github.com/Rdatatable/data.table/issues/2406

I hope this helps.

Cheers,
Hajk
